export const HANDLE_CHANGE_VALUE = "@conversations/handle change value"
export const CLEAR_MESSAGE_VALUE = "@conversations/clear message value"
export const ADD_ROOM = "@conversations/add room"
export const REMOVE_CONVERSATION = "@conversations/delete conversation"
export const GET_CONVERSATIONS = "@conversations/get conversations fb"
